site_name: "MEDEA  documentation"
site_url: "https://medea.docs.rokubun.cat"
theme:
  name: material
  logo: 'https://www.rokubun.cat/assets/images/medea_logo.png'
  favicon: 'images/favicon.ico'
  palette:
    primary: 'deep orange'
    accent: 'blue grey'
  custom_dir: 'custom'
  rokubun_url: 'https://www.rokubun.cat'
nav:
  - 'Description': index.md
  - 'Log format': format.md
extra_css:
  - 'stylesheets/extra.css'
repo_name: 'rokubun/medea-docs'
repo_url: 'https://github.com/rokubun/medea-docs'
extra:
  social:
    - type: 'globe'
      link: 'https://www.rokubun.cat'
    - type: 'twitter'
      link: 'https://twitter.com/rokubn'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/company/rokubun/'